### ISSUE TITLE
Add text

### ISSUE THREAD

**Issue by Hatman42** [swoo32/xGraphics-Python-Game-engine#1]
Text should be added

Tried using `turtle.write("Made by swoo32", font=("Arial", 16, "normal"))` but couldn't get it to work. Try adding text to the game please, but any way to make the code work?

**Comment by swoo32** [comment]
I don't know the command for adding text in turtle, I'll look into that later.

**Comment by Hatman42** [comment]
alright.

**Comment by Hatman42** [comment]
Have you found it yet?

**Comment by Hatman42** [comment]
Nobody here commenting so i'll just close the issue.
